# Generated by Django 4.2.2 on 2023-07-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="fullname",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
